HMS/HMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hotel.urls')),
    path('accounts/', include('allauth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

HMS/hotel/urls.py
from django.urls import path
from .views import RoomListView,BookingListView,RoomDetailView,CancelBookingView,BookingFormView,contact_us,about_us,gallery
app_name='hotel'
urlpatterns=[
    path('room_list/',RoomListView,name='RoomListView'),
    path('booking_list/',BookingListView.as_view(),name='BookingListView'),
    path('room/<category>',RoomDetailView.as_view(),name='RoomDetailView'),
    path('booking/cancel/<pk>',CancelBookingView.as_view(),name='CancelBookingView'),
    path('', BookingFormView, name='BookingFormView'),
    path('contact-us/', contact_us, name="contact_us"),
    path('about-us/', about_us, name="about_us"),
    path('gallery/',gallery,name='gallery')
]

HMS/hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
import datetime
# Create your models here.
class Room(models.Model):
    ROOM_CATEGORIES=(
        ('SIN','SINGLE'),
        ('DBL','DOUBLE'),
        ('DEL','DELUXE'),
        ('KIN','KING'),
        ('QUE','QUEEN'),
        ('NAC','NON-AC'),
    )
    rate = models.FloatField()
    number =models.IntegerField()
    category=models.CharField(max_length=3,choices=ROOM_CATEGORIES)
    beds=models.IntegerField()
    capacity=models.IntegerField()
    def __str__(self):
        return f'room number: {self.number} ,category:{self.category} with {self.beds} for {self.capacity} people at rs {self.rate}/day'

class Booking(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    room= models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in=models.DateTimeField()
    check_out = models.DateTimeField()
    name = models.CharField(max_length=100)
    email = models.EmailField()
    number=models.IntegerField()
    total_price=models.FloatField()
    def __str__(self):
        return f'{self.name} has booked {self.room} from {self.check_in} to {self.check_out} \n total_price:{self.total_price}'

    def get_room_category(self):
        room_categories=dict(self.room.ROOM_CATEGORIES)
        room_category=room_categories.get(self.room.category)
        return room_category
    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

HMS/hotel/forms.py
from django import forms
class AvailabilityForm(forms.Form):
    """"
    ROOM_CATEGORIES = (
        ('SIN', 'SINGLE'),
        ('DBL', 'DOUBLE'),
        ('DEL', 'DELUXE'),
        ('KIN', 'KING'),
        ('QUE', 'QUEEN'),
        ('NAC', 'NON-AC'),
    )
    room_category=forms.ChoiceField(choices=ROOM_CATEGORIES,required=True)
    """
    check_in=forms.DateTimeField(required=True,input_formats=["%d-%m-%YT%H:%M",])
    check_out = forms.DateTimeField(required=True, input_formats=["%d-%m-%YT%H:%M", ])
    name=forms.CharField(required=True)
    number=forms.IntegerField(required=True)
    email=forms.EmailField(required=True)

HMS/hotel/views.py
from django.shortcuts import render,HttpResponse
from django.views.generic import  ListView,FormView,View,DeleteView
from .models import  Room,Booking
from hotel.booking_functions.availability import check_availability
from hotel.booking_functions.find_total_room_charge import find_total_room_charge
from .forms import AvailabilityForm
from django.urls import reverse,reverse_lazy

def BookingFormView(request):
    return render(request, 'booking_form.html',{'user':request.user})


def RoomListView(request):
    room=Room.objects.all()[0]
    room_categories= dict(room.ROOM_CATEGORIES)
    room_values=room_categories.values()
    room_list=[]
    for room_category in room_categories:
        room=room_categories.get(room_category)
        room_url=reverse('hotel:RoomDetailView',kwargs={'category':room_category})
        room_list.append((room,room_url))

    context={
        'room_list':room_list,
    }
    return render(request,'room_list_view.html',context)
class BookingListView(ListView):
    model = Booking
    template_name = "booking_list_view.html"
    def get_queryset(self,*args,**kwargs):
        if self.request.user.is_staff:
            booking_list=Booking.objects.all()
            return booking_list
        else:
            booking_list=Booking.objects.filter(user=self.request.user)
            return booking_list
class RoomDetailView(View):
    def get(self, request, *args, **kargs):
        category=self.kwargs.get('category',None)
        form=AvailabilityForm()
        room_list = Room.objects.filter(category=category)
        if len(room_list)>0:
            room=room_list[0]
            room_category=dict(room.ROOM_CATEGORIES).get(room.category,None)
            context = {
                'room_category': room_category,
                'form':form
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('category does not exist')




    def post(self, request, *args, **kargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form=AvailabilityForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']): #and not(is_room_booked(room)):
                available_rooms.append(room)
        if len(available_rooms) > 0:
            room = available_rooms[0]
            total_price = find_total_room_charge(data['check_in'], data['check_out'], category)
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out'],
                name=data['name'],
                email=data['email'],
                number=data['number'],
                total_price=total_price,
            )
            booking.save()

            return HttpResponse(booking)
        else:
            return HttpResponse('all rooms of this category are booked, plz try another one')



class CancelBookingView(DeleteView):
    model=Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('hotel:BookingListView')
def contact_us(request):
    return render(request, 'contact_us.html')
def about_us(request):
    return render(request, 'about_us.html')
def gallery(request):
    room=Room.objects.all()[0]
    room_categories= dict(room.ROOM_CATEGORIES)
    room_values=room_categories.values()
    room_list=[]
    for room_category in room_categories:
        room=room_categories.get(room_category)
        room_url=reverse('hotel:RoomDetailView',kwargs={'category':room_category})
        room_list.append((room,room_url))

    context={
        'room_list':room_list,
    }
    return render(request,'gallery.html',context)

HMS/hotel/templates/about_us.html
{% extends "layout.html" %}
{% load static %}
{% block title%}
    ABOUT US
{% endblock %}
{% block links %}
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/about_us.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
{% endblock %}
{% block content%}
<a href="{% url 'hotel:BookingFormView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>

    <div >
        <h1>ABOUT MARINA HOTEL:</h1>
        <h3>Enabling authentic indigenous experiences in harmony with environment & society</h3>

        <p> Marina Hotel is an archetype of the culture and ethos of the region that it is located in. The concept of each of the hotels weaves in the strongest elements of the culture of the region – harking back through architecture, interiors, art and artefacts to the major dynasties who have ruled India.</p>
        <p>The unique value propositions, including the differentiated character of hotels, coupled with indigenous experiences is what makes MARINA Hotel unique.</p>
        <p>India’s centuries-rooted sacred relationship with its environment, of sustenance and nurture, is a vital and living heritage that is the cornerstone of the MARINA Hotel ethos and an affirmation of Responsible Luxury: luxury without compromising the earth and sustainability without compromising luxury. </p>
        <p>Responsible Luxury is the effective combination of luxury and responsible practices (enriching society and the environment) so that the luxury experiences delivered at MARINA Hotel do not in any way burden the environment or the society around us. In fact, it is aimed at creating a positive impact on both the community-at-large and the environment.</p>
        <p>It ensures that sustainable practices are built into our hotels in the design phase itself, thus enabling MARINA Hotels to be eco-embedded, services to be eco-easy and our associates to be eco-sensitised; all of this while ensuring you indulge guilt-free.MARINA Hotel is LEED Platinum certified. </p>
        <p>Welcome to planet positive luxury experiences by MARINA Hotel.</p>
    </div>
    <div id="img" >
        <img src="https://www.itchotels.com/content/dam/itchotels/in/umbrella/itc/hotels/itcgrandgoa-goa/images/wellbeing-landing-page/headmast-mobile/wellbeing.png" >

    </div>
{% endblock %}

HMS/hotel/templates/booking_cancel_view.html
{% extends "layout.html" %}
{% load static %}
{% block title%}
    BOOKING CANCEL
{% endblock %}
{% block links %}
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">
{% endblock %}
{% block content%}
      <div class="content">
        <div class="image">
            <img src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>


        <div class="room">
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <h3>DETAILS:</h3>
                <h3>ROOM NUMBER:{{booking.room.number}} , CATEGORY:{{booking.get_room_category}} </h3>
                <h3>{{booking}}</h3>

            </div>


            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you wanna cancel this Booking? </h2>
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div>

    </div>
{% endblock %}

HMS/hotel/templates/booking_form.html
{% extends "layout.html" %}
{% load static %}
{% block title%}
    HOME PAGE
{% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'hotel/css/booking_form.css' %}"/>
{% endblock %}
{% block content%}
      <div class="check_availability">
        <div class="heading">
          <h1 style="font-size:3.5rem;">Marina Hotel</h1>
        </div>
      </div>
{% endblock %}

HMS/hotel/templates/contact_us.html
{% extends "layout.html" %}
{% load static %}
{% block title%}
    CONTACT US
{% endblock %}
{% block links %}
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <link rel="stylesheet" href="{% static 'hotel/css/contact_us.css' %}">
{% endblock %}
{% block content%}
<div>
      <a href="{% url 'hotel:BookingFormView' %}"><i class="fas fa-arrow-alt-circle-left" >Home</i></a>

    <h1><i class="far fa-address-card"></i>CONTACT US@</h1>
    <h3>In case of any queries or reservation requests please reach out to our Guest Contact Centre</h3>
    <h3>Toll-free number (Valid for guest calling from within India)</h3>
    <h3>1-800-419-6444 ; 1-800-102-2333</h3>
    <h3>Direct number (Valid for guest calling from outside India)</h3>
    <h3>+91124 4816900; +91124 6718000</h3>
    <a href="mailto:reservations@marinahotels.in" target="_blank">
        <i class="far fa-envelope"></i>
    </a>
    <span>reservations@marinahotels.in</span>
    </div>
{% endblock %}

{% load static %}
<!--<body style="background-image:linear-gradient(blue,purple);background-repeat:no-repeat;" >-->

<!--    -->


<!--</body>-->
<!--</html>-->

HMS/hotel/templates/header.html
<div class="nav">
      <h3 id="logo">Marina</h3>
      <nav>
          {%block back%}
          {% endblock %}
        <a  href="{% url 'hotel:about_us' %}">ABOUT</a>
        <a  href="{% url 'hotel:contact_us' %}">CONTACT</a>
        <a  href="{% url 'hotel:gallery' %}">GALLERY</a>
        <a  href="{% url 'hotel:RoomListView' %}">BOOK NOW</a>
        <a  href="{% url 'hotel:BookingListView' %}">MY BOOKINGS</a>
          {% if user.email %}
            <a  href="http://127.0.0.1:8000/accounts/logout/">LOGOUT</a>
          {% else %}
            <a  href="http://127.0.0.1:8000/accounts/login/">SIGN IN</a>
            <a  href="http://127.0.0.1:8000/accounts/signup/">SIGN UP</a>
          {% endif %}
      </nav>
</div>

HMS/hotel/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}  {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'hotel/css/header.css' %}"/>
    <link rel="stylesheet" href="{% static 'hotel/css/footer.css' %}"/>
    {% block links%}  {% endblock %}
</head>
<body>
    {% include "header.html" %}
    {% block content%}  {% endblock %}
    {% include "footer.html" %}
</body>
</html>

HMS/hotel/templates/room_detail_view.html
{% extends "layout.html" %}
{% load static %}
{% block title%}
    ROOM DETAIL
{% endblock %}
{% block links %}
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">
{% endblock %}
{% block content%}
      <div class="content">
        <div class="image">
            <img src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>
        <div class="room">
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>
            <div class="room-info">
                {% if room_category == "SINGLE" %}
                   <h2>{{room_category}} </h2>
                   <p>BEDS:1, CAPACITY:1, PRICE:RS 1500/day</p>
                {% elif room_category == "DOUBLE" %}
                   <h2>{{room_category}} Suite</h2>
                   <p>BEDS:2, CAPACITY:2, PRICE:RS 2500/day</p>
                   <p>YOU ALSO A GET COMPULSORY BREAKFAST </p>
                {% elif room_category == "KING" %}
                   <h2>{{room_category}} Suite</h2>
                   <p>BEDS:2, CAPACITY:4, PRICE:RS 4000/day</p>
                   <p>YOU ALSO A GET COMPULSORY BREAKFAST AND EXTRA BEDDINGS FOR CHILDREN</p>
                {% elif room_category == "QUEEN" %}
                   <h2>{{room_category}} Suite</h2>
                   <p>BEDS:2, CAPACITY:3, PRICE:RS 3500/day</p>
                   <p>YOU ALSO A GET COMPULSORY BREAKFAST AND SPACIOUS ROOM</p>
                {% elif room_category == "DELUXE" %}
                   <h2>{{room_category}} Suite</h2>
                   <p>BEDS:3, CAPACITY:5, PRICE:RS 6000/day</p>
                   <p>YOU ALSO A GET COMPULSORY BREAKFAST AND TWO CONNECTING ROOMS </p>
                {% elif room_category == "NON-AC" %}
                   <h2>{{room_category}} Suite</h2>
                   <p>BEDS:2, CAPACITY:2, PRICE:RS 1000/day</p>
                {% endif %}
            </div>
            <form id="booking-form" action="" method="POST">
                {% csrf_token %}
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>
                <div class="input-div">
                    <label>NAME : </label>
                    <input type="text" name="name">
                </div>
                <div class="input-div">
                    <label >EMAIL : </label>
                    <input type="email" name="email" placeholder="abc@xyz.com">
                </div>
                <div class="input-div">
                    <label>MOBILE NO : </label>
                    <input type="number" name="number" placeholder="8720387780">
                </div>

                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>


        </div>

    </div>
{% endblock %}